var arr=
[
    {heading:"Calories Burned Swimming Calculator",paragraph:"Check out how many calories you have burned during swimming. The result of calorie count is based on your average metabolic rate, weight and minutes spent swimming, speed, and swimming stroke."},
    {heading:"Water Intake Calculator: How Much Water Should I Drink?   ",paragraph:"Find out how much amount of water that you need to consume based on your exercise time and your body weight using the Water Intake Calculator."},
    {heading:"Calories Burned Running Calculator",paragraph:"Calories Burned Running Calculator is used to measuring the calories that you have burned by running one mile, two miles, three miles or more. The result is calculated based on your weight, time spent running and distance run."},    
    {heading:"Ketogenic Calculator For Diet",paragraph:"Ketogenic Calculator helps in estimating the accurate amount of proteins, fats and carbohydrates that are required for you to achieve your desired weight through the keto diet."},    
    {heading:"Carbohydrate Calculator",paragraph:"For all those who are willing to eat healthy, this carbohydrate calculator is an excellent tool. It helps you in calculating the total number of carbs per day you need to take in order to maintain a balanced diet and stay healthy."},    
    {heading:"Bra Size Calculator – Step By Step Guide To Measure",paragraph:"The toughest thing for every woman is to choose the right bra.This Bra Size Calculator.Will help you in knowing the right size and give you a better solution."},    
    {heading:"Calories Burned Biking Calculator",paragraph:"Calories Burned Biking tool will help you in estimating the calories burned on your last bike ride by considering parameters like your weight, speed distance covered and time spent biking."},    
    {heading:"Shoe Size Calculator",paragraph:"Shoe Size Calculator tool will help you in converting your shoe size from US to UK and vice versa will buying shoes online. You can convert shoe size for women, men and children."},    
    {heading:"Calories Burned Hiking Calculator",paragraph:"Calorie Burn Hiking Tool estimates the calories you burned on your hike considering few parameters such as your average metabolic rate, your weight along with backpack weight if any, the distance you hiked and time of hiking."},    
    {heading:"One Rep Max Calculator",paragraph:"The Purpose of using One Rep Max Calculator is to calculate the max weight you can lift for a single repetition (1RM). The result is calculated based on the weight of the lift you carry."},    
    {heading:"Yoga Calories Burned Calculator",paragraph:"The yoga calorie burn calculator is used to quickly calculate the number of calories you are likely to burn during a yoga session by considering your average metabolic rate based on your weight, yoga type and total minutes you performed yoga for."},    
    {heading:"Zumba Calories Burned Calculator",paragraph:"Zumba calories Burn calculator estimated the number of Zumba calories you have burned during the Zumba Fitness class. The calculation is based on your weigh, workout time and intensity of the workout."},    
    {heading:"Bench Press Calculator",paragraph:"This bench press tool is used to calculate your approximate 1 REP MAX bench press by counting the amount of weight you can bench along with the number of repetitions."},    
    {heading:"Love Compatibility Calculator",paragraph:"Prank on your friends and dear ones using this Love Calculator Prank. The results of the calculation are sent to your registered mail id. Know who has a crush on whom!!"},    
    {heading:"Body water Calculator",paragraph:"This body water calculator estimates the volume of water in your body. The value is obtained using your age, height, weight, and sex as parameters. This calculation is based on a formula developed by dr. P.E. Watson."},    
    {heading:"Sleep Cycle Calculator: What Time to Go to Bed and Wake Up",paragraph:"Sleep Calculator helps you to find out what time you need to sleep if you want to wake up fresh. Check out the best bedtime for you and maximize your full sleep cycles."},    
    {heading:"Creatinine Clearance Calculator",paragraph:"This Creatinine Clearance Tool is designed based on the creatinine clearance formula (Cockcroft-Gault equation). The calculation is based on the estimates of glomerular filtration rate (GFR)."},    
    {heading:"Caffeine Calculator",paragraph:"Caffeine Calculator Calculates the amount of caffeine you can take during a day. Checkout if you should stop drinking coffee or drink more than one cup to regain your energy."},    
    {heading:"MELD Calculator",paragraph:"The MELD calculator is used to identify MELD scores and prioritize patients with end-stage liver disease for transplant planning. This calculator is not suitable for children below 12 years."},    
    {heading:"LDL Cholesterol Calculator",paragraph:"Calculate the amount of Low-Density Lipoproteins using LDL Calculator as the concentration of Lipoproteins is a very important parameter predicting the arteriosclerotic risk. "},    
    {heading:"Diabetes Risk Calculator",paragraph:"The diabetes risk calculator allows you to estimate your risk of developing diabetes based on a few clinical and socio demographic data. Check out if you are in a high risk group of developing type 2 diabetes."},    
    {heading:"Cholesterol Ratio Calculator",paragraph:"The Cholesterol Ratio Calculator helps you to quickly analyze your blood reports and calculates the cholesterol indicators (LDL and HDL levels) and assess the risk of heart disease and helps in maintaining your overall health."},    
    {heading:"US Navy Body Fat Calculator",paragraph:"The Navy Body Fat Calculator is designed by US Navy according to the standards and conditions of military services. This calculator determines the percent body fat in accordance with the percentage of fat a navel service member must-have. "},    
    {heading:"Normal Urine Output Calculator",paragraph:"The urine output calculator calculates your urine output based on your fluid intake. The urine output rate is measured in per kg per hour based on the fluid balance."},    
    {heading:"Overweight Calculator",paragraph:"Calculate your overweight status using Overweight Calculator. Overweight can be termed based on the increase in body weight with respect to height. Considering parameters like age, gender, weight and height overweight is determined."},    
    {heading:"BMI Calculator: Chart And How To Calculate Body Mass Index?",paragraph:"Checkout your body mass either you are lean or fat using this BMI calculator. BMI Calculator determines whether you are in a healthy zone or not."},    
    {heading:"BMR Calculator (Basal Metabolic Rate) and Daily Calories You Needed",paragraph:"Know your body mass ratio using the BMR calculator and check out the calorie intake to build your body mass. Follow the proper diet based on the results obtained."},    
    {heading:"Body Fat Calculator",paragraph:"Check your body fat using the Body Fat Calculator. This calculator estimates your total body fat based on a few values such as Age, Gender, Height, weight, Neck, waist and hip sizes. "},    
    {heading:"Ideal Body Weight Calculator",paragraph:"Determine your ideal body weight using Body considering factors like gender, age, and height. Checkout out your ideal weight and possible risks associated with it."},    
    {heading:"Running Pace Calculator",paragraph:"Determine your running pace or your pace per mile for a given distance using this runner’s pace calculator. The result is obtained by considering two variables (Pace and Distance). This calculator is useful for both new runners and expert runners."},    
    {heading:"Target Heart Rate Calculator Chart",paragraph:"Heart Rate Calculator is used to find out your target heart rate based on the values of your resting heart rate. The medically-based Karvonen formula is used to estimate the target heart rate."},    
    {heading:"Protein Intake Calculator: How Much Protein Should You Eat Per Day?",paragraph:"Protein Calculator helps you to estimate the amount of dietary protein required for an adult to stay healthy. The calculator is useful for monitoring protein intake. "},    
    {heading:"Age Calculator",paragraph:"The age calculator is used to determine the interval between the specified two days. The age calculated can be displayed in various forms (Days, months, years and weeks). This calculator is based on the most common age system."},    
    {heading:"Blood Alcohol Content (BAC) Calculator: Wine, Beer And Other Alcohols",paragraph:"Blood Alcohol Content (BAC) Calculator measures the percentage of alcohol present in a person’s bloodstream, and this can be measured by type of alcohols and time of drinking. This calculator gives you an approximate BAC level. "},    
    {heading:"Pregnancy Weight Gain Calculator",paragraph:"The Institute of Medicine has set some guidelines for a healthy weight gain during pregnancy. This Pregnancy Weight Gain Calculator estimates the significant changes to women’s body and ensures weight gain. "},    
    {heading:"BSA (Body Surface Area) Calculator",paragraph:"Body Surface Area Calculator is used to calculate your body surface area (BSA). It is used for clinical purposes such as determining cardiac index, dosages for chemotherapy. The results are obtained based on several metric formulas."},    
    {heading:"GFR Calculator (Glomerular Filtration Rate)",paragraph:"GFR calculator is the best tool to index your kidney function. It is used to calculate your glomerular filtration rate (GFR) by taking a few parameters such as age, sex, and body size."},    
    {heading:"Waist to Hip Ratio (WHR) Calculator – WHR Chart",paragraph:"Checkout your belly fat using waist to hip ratio calculator. The calculation is done according to WHO standards considering waist and hip measurements."},    
    {heading:"Army Body Fat Calculator",paragraph:"The Army Body Fat Calculator will determine your body fat percentage in accordance with army recruitment standards and defence goals. To maintain accuracy the average of least three measurements is taken. "},    
    {heading:"Weight Gain Calculator",paragraph:"It is the ideal way to manage your weight gain or weight loss by calculating your calorie intake only with several metrics such as height, weight, BMR, and your activity level. Manage your diet based on these results."},    
    {heading:"Resting Metabolic Rate (RMR) Calculator",paragraph:"Using Resting Metabolic Rate Calculator find out your Resting Metabolic Rate (RMR) and know kCal intake per day you require while you are resting."},    
    {heading:"Fat Intake Calculator: How Much Fat Per Day Is Needed?",paragraph:"Fat Intake Calculator estimates the amount of dietary fat to be consumed based on daily caloric needs by considers the recommended levels of saturated fats a person should consume to reduce the risk of heart disease."},    
    {heading:"Steps to Miles Calculator: How Many Steps Are In a Mile?",paragraph:"Steps to Miles Calculator will help you calculate the number of steps you’ve walked as well as know the number of steps you need to walk. The calculation is based on your height, gender, and pace."},    
    {heading:"Weight Watchers Points Calculator",paragraph:"Weight Watchers Points calculator used to estimate the point value of a food with known parameters. The points will help people lose weight in a controlled way based on a person’s overall lifestyle and eating habits."},    
    {heading:"Fat Free Mass Index (FFMI) Calculator",paragraph:"The fat-free mass index (FFMI) calculator will help you in measuring the muscle mass index and discover the score indicated and check your muscle mass whether it is natural or steroid muscle mass build-up by fitness enthusiasts."},    
    {heading:"Wilks Calculator In kg and lbs",paragraph:"Wilks Calculator will help you in calculating your Wilks points to compare your relative strength level while performing deadlifts. It gives a fair indication of relative strength irrespective of the different weights the lifters lift."},    
    {heading:"Lean Body Mass Calculator",paragraph:"Lean Body Mass Calculator estimates the lean body mass (LBM) of a person’ based on their body gender, age, height, and weight. The calculations provided based on the results of multiple formulas."},    
    {heading:"Cooking Time Calculator",paragraph:"This easy-to-use cooking time calculator will help you in finding the temperature and ideal cooking time for roasting your beef, chicken, pork, goose, venison, lamb, turkey, or duck based on the weight of the meat."},    
    {heading:"Female Body Shape Calculator",paragraph:"Female Body Shape Calculator helps you to determine your body type based on some international metrics considering your bone structure and fat decomposition. This is the ideal way to know your body shape and reshape your figure."},    
    {heading:"Period Calculator",paragraph:" Period Calendar helps you to easily track your period and ovulation days based on the length of your mensural cycle and the previous dates of your period."},    
    {heading:"Gestational Age Calculator",paragraph:"Calculate your Gestational Age of your baby using this Gestational Age calculator. The time is calculated based on the first day of the mother’s last menstrual period to the estimated date of delivery."}
];
arr.map(function(elem)
{
    var div=document.createElement("div");
    div.id='four';
    div.style.border='2px solid #efefef';
    var head=document.createElement("h2");
    head.innerText=elem.heading;
    var par=document.createElement("p");
    par.innerText=elem.paragraph;
    var read=document.createElement("a");
    read.innerText="--Read More";
    read.id='Three';
    div.append(head,par,read);
    document.getElementById("Ttwo").append(div);
});
